### ISSUE TITLE
QrPaymentReferenceGenerator::generate

### ISSUE THREAD

**Issue by FredBoard** [sprain/php-swiss-qr-bill#168]
Hi, the QrPaymentReferenceGenerator::generate return 
`Fatal error: Uncaught Sprain\SwissQrBill\Validator\Exception\InvalidQrPaymentReferenceException: The provided data is not valid to generate a qr payment reference number. in /home/httpd/vhosts/preprod.info/bill-v3.preprod.info/vendor/sprain/swiss-qr-bill/src/Reference/QrPaymentReferenceGenerator.php:51 Stack trace: #0 /home/httpd/vhosts/preprod.info/bill-v3.preprod.info/vendor/sprain/swiss-qr-bill/src/Reference/QrPaymentReferenceGenerator.php(27): Sprain\SwissQrBill\Reference\QrPaymentReferenceGenerator->doGenerate() #1 /home/httpd/vhosts/preprod.info/bill-v3.preprod.info/GAR_Master_def.php(1283): Sprain\SwissQrBill\Reference\QrPaymentReferenceGenerator::generate('NULL', '1234') #2 /home/httpd/vhosts/preprod.info/bill-v3.preprod.info/GAR_Factures.php(102): build_billing_little_pdf('214') #3 {main} thrown in /home/httpd/vhosts/preprod.info/bill-v3.preprod.info/vendor/sprain/swiss-qr-bill/src/Reference/QrPaymentReferenceGenerator.php on line 51 `

My banking provider is Postfinance ... for this reason i have try with NULL 'NUL' '' nothing ... but always a Fatal error.

`// Add payment reference
// This is what you will need to identify incoming payments.
$referenceNumber = QrBill\Reference\QrPaymentReferenceGenerator::generate(
    'NULL',  // You receive this number from your bank (BESR-ID). Unless your bank is PostFinance, in that case use NULL.
    '1234' // A number to match the payment with your internal data, e.g. an invoice number
);`

A idea what is wrong ?
Br Fred

**Comment by FredBoard** [comment]
For Exemple , here is a internal reference with Custom data 10000000002892022100504580.
Is the modulo 10 check number also necessary (here 9) at the end  => 10000000002892022100504580**9** ,or  compute self this checksum ?

**Comment by FredBoard** [comment]
I have found the problem ...
there was a incompatibility with **setPaymentReference**

Solution 👍 

`if (get_business_param($BID,'nr_reference_bill'))
{
$referenceNumber = QrBill\Reference\QrPaymentReferenceGenerator::generate( NULL,''.$data100['bv_ref_nr'].'');
$qrBill->setPaymentReference(QrBill\DataGroup\Element\PaymentReference::create(
         QrBill\DataGroup\Element\PaymentReference::TYPE_QR,$referenceNumber));
}else{
$qrBill->setPaymentReference(QrBill\DataGroup\Element\PaymentReference::create(QrBill\DataGroup\Element\PaymentReference::TYPE_NON));
}`

Please close the issue.
Br
Fred
